try {
  a;
} catch (error) {
  console.log("err :" + error);
} finally {
  console.log("a");
}
